### ISSUE TITLE
UncaughtException from lesson 4

### ISSUE THREAD

**Issue by SubCisco** [lmammino/aws-lambda-workshop#1]
error: uncaughtException: Unexpected token { date=Thu Aug 17 2017 12:54:09 GMT+0530 (IST), pid=1199, uid=1000, gid=1000, cwd=/home/subha/aws-lambda-workshop/lessons/05-weather-scrape-schedule, execPath=/usr/bin/nodejs, version=v4.2.6, argv=[/usr/bin/nodejs, /usr/local/bin/lambda-local, -l, src/handler.js, -h, handler, -e, sample-event.json], rss=24350720, heapTotal=10504544, heapUsed=6020008, loadavg=[0.0771484375, 0.06591796875, 0.07861328125], uptime=27574, trace=[column=16, file=vm.js, function=exports.runInThisContext, line=53, method=runInThisContext, native=false, column=25, file=module.js, function=Module._compile, line=374, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=417, method=.js, native=false, column=32, file=module.js, function=Module.load, line=344, method=load, native=false, column=12, file=module.js, function=Module._load, line=301, method=_load, native=false, column=17, file=module.js, function=Module.require, line=354, method=require, native=false, column=17, file=internal/module.js, function=require, line=12, method=null, native=false, column=22, file=/usr/local/lib/node_modules/lambda-local/lib/lambdalocal.js, function=Object._executeSync, line=102, method=_executeSync, native=false, column=22, file=/usr/local/lib/node_modules/lambda-local/lib/lambdalocal.js, function=Object._execute [as execute], line=29, method=_execute [as execute], native=false, column=17, file=/usr/local/lib/node_modules/lambda-local/bin/lambda-local, function=null, line=92, method=null, native=false], stack=[SyntaxError: Unexpected token {,     at exports.runInThisContext (vm.js:53:16),     at Module._compile (module.js:374:25),     at Object.Module._extensions..js (module.js:417:10),     at Module.load (module.js:344:32),     at Function.Module._load (module.js:301:12),     at Module.require (module.js:354:17),     at require (internal/module.js:12:17),     at Object._executeSync (/usr/local/lib/node_modules/lambda-local/lib/lambdalocal.js:102:22),     at Object._execute [as execute] (/usr/local/lib/node_modules/lambda-local/lib/lambdalocal.js:29:22),     at /usr/local/lib/node_modules/lambda-local/bin/lambda-local:92:17]

**Comment by lmammino** [comment]
At a first glance, it looks like have a syntax error. Are you sure you copied everything correctly?

**Comment by SubCisco** [comment]
Hi
 I got this iss.ue resolved. Teh main issue was my apt-get update had issues and hence I had installed an older version of Nodejs which 4.2.6. After upgrading the Nodejs to the latest version, it was resolved. Thanks

**Comment by lmammino** [comment]
Glad to know you solved it
