### ISSUE TITLE
AWS CloudForation AccessDenied for createChangeset

### ISSUE THREAD

**Issue by SubCisco** [lmammino/aws-lambda-workshop#2]
An error occurred (AccessDenied) when calling the CreateChangeSet operation: User: arn:aws:iam::984595728250:user/<Subha> is not authorized to perform: cloudformation:CreateChangeSet on resource: arn:aws:cloudformation:us-east-1:984595728250:stack/simple-hello-world/*

Can you please help

**Comment by lmammino** [comment]
This looks like a permission error (current user not having authorization to perform cloudformation create change set operations).

Are you in your own AWS account (created by yourself) or are you using a user in somebody else account?

In the former case it's a good approach to create a new user (not the root - default - user) and give it admin right. Of course be sure use a complex password and enable MFA for extra security.

Then you need to re-authenticate your cli with:

```bash
aws configure
```

**Comment by lmammino** [comment]
Closing this one as you sorted it out (afaik). Feel free to re open if you have more related concerns
