### ISSUE TITLE
Provide Samlpe API Gateway URL

### ISSUE THREAD

**Issue by SubCisco** [lmammino/aws-lambda-workshop#3]
Can you please provide sample GET https://<> for helloworld

**Comment by lmammino** [comment]
Hello @SubCisco, thanks for your contribution.

Am api gateway URL looks like this:

```
https://<GATEWAY_ID>.execute-api.<REGION>.amazonaws.com/<STAGE>/<ENDPOINT_PATH>
``` 

Where:

 - `GATEWAY_ID`: is the id of the used API gatway
 - `REGION`: the region where the API gateway is installed (e.g. `eu-west-1`)
 - `STAGE`: the deployment stage (e.g. `production` or `test`)
 - `ENDPOINT_PATH`: the endpoint where you installed your specific API (e.g. `/hello/world`)

**Where do you think displaying this information will be more useful?**

Also take into account that I have [a presentation for these tutorials](https://docs.google.com/presentation/d/1_EAX7toXJ90uGNNfE7Aa5Mdd1PBgcuRLBddZQkCztjY/edit) that includes a lot of details that are missing here (for practicality).

**Comment by SubCisco** [comment]
Thanks for the PPT. Yes that error was Permission error

**Comment by lmammino** [comment]
Great. I am closing this one for now. Feel free to re open if you have other related requests
